Scheduler/Scheduler/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('base.urls')),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('schedules/', include(('schedules.urls', 'schedules'), namespace='schedules')),
    path('admin/', admin.site.urls),
]

Scheduler/accounts/urls.py
from django.urls import path

from .views import RegisterView, LogoutView
from django.contrib.auth.views import LoginView


urlpatterns = [
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
]

Scheduler/base/urls.py
from django.urls import path
from .views import home_view


urlpatterns = [
    path('', home_view, name='home'),
]

Scheduler/schedules/urls.py
from django.urls import path

from .views import create_edit_view, detail_view, my_list_view


urlpatterns = [
    path('create/', create_edit_view, name='create'),
    path('edit/<str:pk>', create_edit_view, name='edit'),
    path('detail/<str:pk>', detail_view, name='detail'),
    path('my-list/', my_list_view, name='my-list'),
]

Scheduler/base/models.py
from django.db import models

# Create your models here.

Scheduler/schedules/models.py
from django.db import models
from django.contrib.auth.models import User
from uuid import uuid4
import os


class Schedule(models.Model):
    id = models.UUIDField(default=uuid4, unique=True, primary_key=True)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)
    schedule = models.JSONField(default=dict)
    class_name = models.CharField(max_length=3)
    school_shift = models.CharField(max_length=100)
    school_name = models.CharField(max_length=100)
    region_name = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.creator}-{self.id}"


Scheduler/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    first_name = forms.CharField(max_length=32, required=True)
    last_name = forms.CharField(max_length=32, required=True)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email']

Scheduler/accounts/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy

from django.views.generic import CreateView
from django.views import View

from django.contrib.auth.models import User
from django.contrib.auth import login, logout

from .forms import RegisterForm


class RegisterView(CreateView):
    model = User
    template_name = "accounts/register.html"
    form_class = RegisterForm
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        valid = super().form_valid(form)
        login(self.request, self.object)
        return valid


class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('home')

Scheduler/base/views.py
from django.shortcuts import render


def home_view(request):
    return render(request, "base/home.html")

Scheduler/schedules/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Schedule
import csv
import io


def create_edit_view(request, pk=None):
    if request.method == 'POST' and not request.FILES:
        schedule = {}

        for key in request.POST.keys():
            if '_' in key and key not in ['class_name', 'school_name', 'region_name', 'school_shift']:
                split_key = key.split("_")

                if split_key[0] not in schedule.keys():
                    schedule[split_key[0]] = [request.POST[key] if request.POST[key] else "-"]
                else:
                    schedule[split_key[0]].append(request.POST[key] if request.POST[key] else "-")

        for key in schedule.keys():
            sorted_value = []
            start, end = 0, 4

            for _ in range(len(schedule[key]) // 4):
                sorted_value.append(schedule[key][start:end])
                start += 4
                end += 4

            schedule[key] = sorted_value

        if pk:
            Schedule.objects.filter(pk=pk).update(
                creator=request.user,
                schedule=schedule,
                class_name=request.POST.get("class_name", "-"),
                school_shift=request.POST.get("school_shift", "-"),
                school_name=request.POST.get("school_name", "-"),
                region_name=request.POST.get("region_name", "-"),
            )

            schedule_obj = Schedule.objects.get(pk=pk)
        else:
            schedule_obj = Schedule.objects.create(
                creator=request.user,
                schedule=schedule,
                class_name=request.POST.get("class_name", "-"),
                school_shift=request.POST.get("school_shift", "-"),
                school_name=request.POST.get("school_name", "-"),
                region_name=request.POST.get("region_name", "-"),
            )

        return redirect("schedules:detail", schedule_obj.pk)
    else:
        if 'file' in request.FILES:
            if request.FILES['file'].name[-4:] == '.csv':
                file = request.FILES['file'].read().decode('utf-8')

                schedule = {
                    "ПОНЕДЕЛЬНИК": [],
                    "ВТОРНИК": [],
                    "СРЕДА": [],
                    "ЧЕТВЕРГ": [],
                    "ПЯТНИЦА": [],
                    "СУББОТА": []
                }

                excel_data = list(csv.DictReader(io.StringIO(file)))

                for i in range(0, len(excel_data), 8):
                    for field in excel_data[i:i+8]:
                        if list(field.values())[0].isnumeric():
                            if i == 0:
                                schedule["ПОНЕДЕЛЬНИК"].append(list(field.values())[1:])
                            elif i == 8:
                                schedule["ВТОРНИК"].append(list(field.values())[1:])
                            elif i == 16:
                                schedule["СРЕДА"].append(list(field.values())[1:])
                            elif i == 24:
                                schedule["ЧЕТВЕРГ"].append(list(field.values())[1:])
                            elif i == 32:
                                schedule["ПЯТНИЦА"].append(list(field.values())[1:])
                            elif i == 40:
                                schedule["СУББОТА"].append(list(field.values())[1:])

                return render(request, 'schedules/edit.html', context={"schedule": schedule})

            context = {
                "format_error": True,
                "weekdays": ["ПОНЕДЕЛЬНИК", "ВТОРНИК", "СРЕДА", "ЧЕТВЕРГ", "ПЯТНИЦА", "СУББОТА"]
            }

            return render(request, 'schedules/create.html', context=context)
        elif pk and 'file' not in request.FILES:
            schedule = get_object_or_404(Schedule, pk=pk)

            context = {
                "updated": schedule.updated,
                "class_name": schedule.class_name,
                "school_shift": schedule.school_shift,
                "school_name": schedule.school_name,
                "region_name": schedule.region_name,
                "schedule": schedule.schedule,
            }

            return render(request, 'schedules/edit.html', context=context)
        else:
            context = {
                "weekdays": ["ПОНЕДЕЛЬНИК", "ВТОРНИК", "СРЕДА", "ЧЕТВЕРГ", "ПЯТНИЦА", "СУББОТА"]
            }

            return render(request, 'schedules/create.html', context=context)


def detail_view(request, pk):
    schedule = Schedule.objects.get(pk=pk)

    if "delete_submit" in request.POST:
        schedule.delete()
        return render(request, 'schedules/delete_success.html')

    context = {
        "updated": schedule.updated,
        "class_name": schedule.class_name,
        "school_shift": schedule.school_shift,
        "school_name": schedule.school_name,
        "region_name": schedule.region_name,
        "schedule": schedule.schedule,
        "schedule_pk": pk,
    }

    return render(request, 'schedules/detail.html', context=context)


def my_list_view(request):
    if request.user.is_authenticated:
        schedules = Schedule.objects.filter(creator=request.user)
        return render(request, 'schedules/my_list.html', context={'schedules': schedules})

Scheduler/accounts/templates/accounts/login.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Home{% endblock title %}

{% block content %}
<div class="container">
    <div class="row mt-4 mb-5">
        <form method="post" class="col-lg-7">
            {% csrf_token %}
            <h6 for="inputUsername" class="form-label fs-5">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-envelope-fill" viewBox="0 0 16 16">
                    <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6"/>
                </svg>
                Имя пользователя
            </h6>
            <input type="text" name="username" class="form-control fs-5 mb-3" id="inputUsername" style="border: 2px solid black">

            <h6 for="inputPassword" class="form-label fs-5">
                <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-lock-fill" viewBox="0 0 16 16">
                    <path d="M8 1a2 2 0 0 1 2 2v4H6V3a2 2 0 0 1 2-2m3 6V3a3 3 0 0 0-6 0v4a2 2 0 0 0-2 2v5a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2"/>
                </svg>
                Пароль
            </h6>
            <input type="password" name="password" class="form-control fs-5 mb-3" id="inputPassword" style="border: 2px solid black">

            <button type="submit" class="btn btn-dark px-5 fs-4 mb-3">Войти</button>
            <div class="fs-5 mb-3" style="font-weight: 500">
                Еще нет аккаунта? <a href="{% url 'accounts:register' %}" class="text-muted fs-5 text-decoration-none">Зарегистрироваться</a>
            </div>
            {% if form.errors %}
            <div class="fs-5 text-danger fw-bold">Возникли ошибки:</div>
            <div class="text-danger">
                <div class="alert alert-danger">
                    {{ form.errors }}
                </div>
            </div>
            {% endif %}
        </form>
    </div>
</div>
{% endblock content%}

Scheduler/accounts/templates/accounts/register.html
{% extends 'base/base.html' %}

{% block title %}Register{% endblock title %}

{% block content %}
<div class="container">
    <div class="row mt-4 mb-5">
        <form method="post" class="col-lg-7">
            {% csrf_token %}
            <h6 for="inputFirstName" class="form-label fs-5">
                <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="currentColor" class="bi bi-envelope-fill" viewBox="0 0 16 16">
                    <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6"/>
                </svg>&nbsp;
                Имя
            </h6>
            <input type="text" name="first_name" class="form-control fs-5 mb-3" id="inputFirstName" style="border: 2px solid black">
            <h6 for="inputLastName" class="form-label fs-5">
                <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="currentColor" class="bi bi-envelope-fill" viewBox="0 0 16 16">
                    <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6"/>
                </svg>&nbsp;
                Фамилия
            </h6>
            <input type="text" name="last_name" class="form-control fs-5 mb-3" id="inputLastName" style="border: 2px solid black">

            <h6 for="inputUsername" class="form-label fs-5">
                <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="currentColor" class="bi bi-envelope-fill" viewBox="0 0 16 16">
                    <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6"/>
                </svg>&nbsp;
                Имя пользователя
            </h6>
            <input type="text" name="username" class="form-control fs-5 mb-3" id="inputUsername" style="border: 2px solid black">

            <h6 for="inputEmail" class="form-label fs-5">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-envelope-fill" viewBox="0 0 16 16">
                    <path d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414zM0 4.697v7.104l5.803-3.558zM6.761 8.83l-6.57 4.027A2 2 0 0 0 2 14h12a2 2 0 0 0 1.808-1.144l-6.57-4.027L8 9.586zm3.436-.586L16 11.801V4.697z"/>
                </svg>&nbsp;
                Электронная почта
            </h6>
            <input type="email" name="email" class="form-control fs-5 mb-3" id="inputEmail" style="border: 2px solid black">

            <h6 for="inputPassword1" class="form-label fs-5">
                <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-lock-fill" viewBox="0 0 16 16">
                    <path d="M8 1a2 2 0 0 1 2 2v4H6V3a2 2 0 0 1 2-2m3 6V3a3 3 0 0 0-6 0v4a2 2 0 0 0-2 2v5a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2"/>
                </svg>
                Пароль
            </h6>
            <input type="password" name="password1" class="form-control fs-5 mb-3" id="inputPassword1" style="border: 2px solid black">
            <h6 for="inputPassword2" class="form-label fs-5">
                <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-lock-fill" viewBox="0 0 16 16">
                    <path d="M8 1a2 2 0 0 1 2 2v4H6V3a2 2 0 0 1 2-2m3 6V3a3 3 0 0 0-6 0v4a2 2 0 0 0-2 2v5a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2"/>
                </svg>
                Пароль (повторно)
            </h6>
            <input type="password" name="password2" class="form-control fs-5 mb-3" id="inputPassword2" style="border: 2px solid black">

            <button type="submit" class="btn btn-dark px-5 fs-4 mb-3">Зарегистрироваться</button>
            <div class="fs-5 mb-3" style="font-weight: 500">
                Уже есть аккаунт? <a href="{% url 'accounts:login' %}" class="text-muted fs-5 text-decoration-none">Войти</a>
            </div>

            {% if form.errors %}
                <div class="fs-5 text-danger fw-bold">Возникли ошибки:</div>
                <div class="text-danger">
                    {% for field in form %}
                        {% for error in field.errors %}
                        <strong>- {{field.label}}:</strong> {{ error|escape }} <br>
                        {% endfor %}
                    {% endfor %}
                </div>
            {% endif %}
        </form>
        <div class="col"></div>
    </div>
</div>
{% endblock content %}

Scheduler/base/templates/base/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
        <title>Scheduler | {% block title %}{% endblock title %}</title>
    </head>
    <body style="font-family: Roboto; font-weight: 400">
        <div class="container fluid mb-4">
            <header class="d-flex flex-wrap justify-content-center pt-3 pb-2 me-3">
                <a href="/" class="d-flex align-items-center mb-3 me-lg-auto link-body-emphasis text-decoration-none">
                    <img src="{% static 'logo.png' %}" class="me-3" width="40" height="40">
                    <span class="fs-4 text-black me-4" style="font-weight: 500">СЧЕДУЛЕР</span>
                </a>
                <ul class="nav nav-pills">
                    <li class="nav-item dropdown mt-1">
                        <a class="nav-link dropdown-toggle text-dark text-decoration-none me-4 fs-5 p-0"
                           style="font-weight: 500" role="button" data-bs-toggle="dropdown" data-bs-theme="dark" aria-expanded="false">
                            РАСПИСАНИЯ
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'schedules:create' %}">Создать новое</a></li>
                            {% if request.user.is_authenticated %}
                            <li><a class="dropdown-item" href="{% url 'schedules:my-list' %}">Мои расписания</a></li>
                            {% endif %}
                        </ul>
                    </li>
                    {% if request.user.is_authenticated %}
                    <li class="nav-item mt-1">
                        <a href="{% url 'accounts:logout' %}" class="text-dark text-decoration-none fs-5"
                           style="font-weight: 500">ВЫХОД
                        </a>
                    </li>
                    {% else %}
                    <li class="nav-item mt-1">
                        <a href="{% url 'accounts:login' %}"
                           class="text-dark text-decoration-none fs-5" style="font-weight: 500">ВОЙТИ
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </header>
            <div style="border: 1px solid #000"></div>
            <div class="main mb-5 position-relative">
                <div class="position-absolute w-100 h-100 page-loader bg-white"
                     style="z-index: 3" id="loading-btn">
                    <button class="btn my-3" type="button" style="pointer-events: none;">
                        <span class="spinner-border text-dark" style="width: 1.3rem; height: 1.3rem;" role="status" aria-hidden="true"></span>
                        <span class="text-dark fs-4" style="font-weight: 500">ЗАГРУЗКА...</span>
                    </button>
                </div>
                {% block content %}{% endblock content %}
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        <script>
            const loadingBtn = document.querySelector("#loading-btn");

            setTimeout(function() {
                loadingBtn.remove();
            }, 1000);
        </script>
    </body>
</html>

Scheduler/base/templates/base/home.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Home{% endblock title %}

{% block content %}
<div class="container text-center">
    <div class="row mb-5">
        <p class="fs-5 mt-4"><strong>СЧЕДУЛЕР (SCHEDULER)</strong> - это веб-приложение, созданное с целью упростить
            создание, управление и рассылку планировок уроков. Сайт предлагает упрощенный вариант
            редактирования расписания благодаря комфортному графическому интерфейсу,
            а ученикам возможность просмотра изменений даже в том случае, когда учитель забыл их отправить в группу класса.
        </p>
    </div>
<!--    <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">-->
<!--        <div class="carousel-inner">-->
<!--            <div class="carousel-item active">-->
<!--                -->
<!--            </div>-->
<!--            <div class="carousel-item">-->
<!--                <img src="..." class="bg-primary d-block w-100" style="height: 300px" alt="">-->
<!--            </div>-->
<!--            <div class="carousel-item">-->
<!--                <img src="..." class="bg-warning d-block w-100" style="height: 300px" alt="">-->
<!--            </div>-->
<!--        </div>-->
<!--        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">-->
<!--            <span class="carousel-control-prev-icon" aria-hidden="true"></span>-->
<!--            <span class="visually-hidden">Previous</span>-->
<!--        </button>-->
<!--        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">-->
<!--            <span class="carousel-control-next-icon" aria-hidden="true"></span>-->
<!--            <span class="visually-hidden">Next</span>-->
<!--        </button>-->
<!--    </div>-->
    <div class="row justify-content-center">
<!--    <img src="{% static 'photo.jpg' %}" class="d-block w-75">-->
        {% for _ in '1234' %}
        <div class="mb-4 col-11" style="border: 2px solid; color: #D3D3D3"></div>
        <div class="mb-4 col-10" style="border: 2px solid; color: #D3D3D3"></div>
        {% endfor %}
        <div class="mb-4 col-11" style="border: 2px solid; color: #D3D3D3"></div>
    </div>
    {% if request.user.is_authenticated %}
        <div class="row mt-5 justify-content-center">
            <h3>Вы уже зарегистрированы, можете приступить к созданию расписания</h3>
            <h5 class="text-muted">Перейдите по ссылке ниже, чтобы начать</h5>
            <a href="{% url 'schedules:create' %}" type="button" class="btn btn-outline-dark w-50 fs-3 mt-4" style="border-width: 3px; font-weight: 500">Создать</a>
        </div>
    {% else %}
        <div class="row mt-5 justify-content-center">
            <h3>Чтобы приступить к созданию, вам необходимо зарегистрироваться</h3>
            <h5 class="text-muted">Вы можете не регистрироваться, если в ваши планы входит лишь просмотр расписаний</h5>
            <a href="{% url 'accounts:register' %}" type="button" class="btn btn-outline-dark w-50 fs-3 mt-4" style="border-width: 3px; font-weight: 500">Регистрация</a>
            <div class="fs-5 mt-4">Уже есть аккаунт? <a href="{% url 'accounts:login' %}" class="text-muted fs-5 text-decoration-none">Войти</a></div>
        </div>
    {% endif %}
</div>
{% endblock content%}

Scheduler/schedules/templates/schedules/create.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Create{% endblock title %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        {% if request.user.is_authenticated %}
        <div class="col-12">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="fs-3 my-3 text-dark text-start">
                    РАСПИСАНИЕ ДЛЯ УЧЕНИКОВ
                    <input type="text" name="class_name" class="fs-3 text-dark mx-1" style="width: 65px; height: 35px" maxlength="3">
                    КЛАССА (
                    <input type="text" name="school_shift" class="fs-3 text-dark mx-1" style="width: 25px; height: 35px" maxlength="1">
                    СМЕНА)
                    <br>
                    ШКОЛА <input type="text" name="school_name" class="fs-3 text-dark mx-1" style="height: 35px">
                    РЕГИОН <input type="text" name="region_name" class="fs-3 text-dark mx-1" style="height: 35px">
                </div>

                <div class="mt-3 fs-5 text-dark text-start">МОЖЕТЕ ЗАГРУЗИТЬ .XLSX ФАЙЛ РАСПИСАНИЯ НИЖЕ</div>
                <div class="input-group w-50 mb-3">
                    <input type="file" class="mb-2 form-control" name="file">
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-dark">Загрузить</button>
                    </div>
                </div>

                {% if format_error %}
                <div class="fs-5 text-danger mb-4"><strong>ОШИБКА:</strong> НЕПОДХОДЯЩИЙ ФОРМАТ ФАЙЛА (ДОЛЖЕН БЫТЬ .CSV)</div>
                {% endif %}

                {% if form.errors %}
                    <div class="my-3" style="border: 1px dashed #000"></div>
                    <div class="fs-2 mb-5" style="font-weight: 300">See your errors below</div>
                    {% for error in form.file.errors %}
                        <p>- {{error}}</p>
                    {% endfor %}
                {% endif %}

                {% for weekday in weekdays %}
                    <div class="fs-5 text-dark text-start" style="font-weight: 500">{{weekday}}</div>
                    <table class="table table-bordered table-hover mb-4 text-center">
                        <thead class="table-dark">
                            <tr>
                                <th>Урок</th>
                                <th>Название</th>
                                <th>Время</th>
                                <th>Каб.</th>
                                <th>Учитель</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% with range='1234567' %}
                        {% for i in range %}
                            <tr>
                                <td>{{i}}</td>
                                <td><input name="{{weekday}}_{{i}}_name" type="text" class="w-75"></td>
                                <td><input name="{{weekday}}_{{i}}_time" type="text" class="w-75"></td>
                                <td><input name="{{weekday}}_{{i}}_cabinet" type="text" class="w-75"></td>
                                <td><input name="{{weekday}}_{{i}}_teacher" type="text" class="w-75"></td>
                            </tr>
                        {% endfor %}
                        {% endwith %}
                        </tbody>
                    </table>
                {% endfor %}

                <button type="submit" class="btn btn-dark fs-4">Создать расписание</button>
            </form>
        </div>
        {% else %}
        <div class="col text-center" style="margin-block: 50px">
            <h3 class="mb-2">
                Перед созданием расписания, вы должны зарегистрироваться<br>
            </h3>

            <a href="{% url 'accounts:register' %}" type="button" class="btn btn-outline-dark w-50 fs-4 mt-4" style="border-width: 3px; font-weight: 500">Регистрация</a>
            <div class="fs-5 mt-4">Уже есть аккаунт? <a href="{% url 'accounts:login' %}" class="text-muted fs-5 text-decoration-none">Войти</a></div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock content%}

Scheduler/schedules/templates/schedules/delete_success.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Successful Deletion{% endblock title %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <h3 class="text-dark">
            Расписание было удалено.
            <a class="text-dark" href="{% url 'home' %}">Вернуться на главную страницу?</a>
        </h3>
    </div>
</div>
{% endblock content%}

Scheduler/schedules/templates/schedules/my_list.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}List{% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
        {% if schedules %}
            <h4 class="my-3">Ниже представлены ваши расписания</h4>
            {% for schedule in schedules %}
                <div class="col-lg-4">
                    <div class="card mt-2 mb-4" id="schedule">
                        <div class="card-body">
                            <h5 class="card-title">
                                Расписание для {{schedule.class_name}} класса ({{schedule.school_shift}} смена)
                            </h5>
                            <h6 class="card-subtitle mb-2 text-muted">
                                Школа - {{schedule.school_name}}<br>
                                Создатель - {{schedule.creator.first_name}} {{schedule.creator.last_name}}<br>
                                Создано - {{schedule.created}}
                            </h6>
                            <a href="{% url 'schedules:detail' schedule.pk %}" class="stretched-link"></a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <h4 class="mt-3">У вас нет никаких расписаний...</h4>
            <a href="{% url 'schedules:create' %}" class="text-muted fs-5 text-decoration-none" style="font-weight: 500">Собираетесь создать?</a>
        {% endif %}
    </div>
</div>
{% endblock content %}